version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    target-branch: 'development'
    labels:
      - 'upgrade dependencies'
    open-pull-requests-limit: 10
    schedule-timezone: 'Asia/Singapore'
