name: NX Monorepo Affected

on:
  workflow_call:
    inputs:
      main-branch-name:
        type: string
        required: true
    outputs:
      services:
        description: 'Service has been affected by PR change'
        value: ${{ jobs.get-affected.outputs.matrix }}

jobs:
  get-affected:
    timeout-minutes: 10
    runs-on: self-hosted
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: '8.x'

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
        id: setSHAs
        with:
          main-branch-name: ${{ inputs.main-branch-name }}

      - name: Identify affected projects
        id: set-matrix
        run: |
          AFFECTED=(`pnpm nx show projects --affected --with-target build --plain --base=$NX_BASE --head=$NX_HEAD`)
          echo "matrix=$(jq --compact-output --null-input '$ARGS.positional' --args "${AFFECTED[@]}")" >> "$GITHUB_OUTPUT"
