name: Build to ECR and Deployment to ECS

on:
  push:
    branches:
      - development
      - uat
      - production

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  get-affected:
    name: Nx Monorepo Affected
    uses: ./.github/workflows/call-affected.yml
    with:
      main-branch-name: ${{ github.head_ref || github.ref_name }}
